substitutions:
  device_name: Haier Appliance
  device_id: haier_test
  uart_id: appliance_port

esphome:
  name: ${device_id}
  comment: ${device_name}
  libraries:
    - pavlodn/HaierProtocol
  includes:
    - haier-test.h

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ${uart_id}

<<: !include test-common.yaml